### ISSUE TITLE
Custom domain: Hard Fail on Permission Error 

### ISSUE THREAD

**Issue by tongueroo** [boltops-tools/jets#557] opened 2021-05-27 15:57 UTC
- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [ ] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System | Cloud9        |
| Jets             | 3.0.5        |
| Ruby             | 2.7.2        |

---

## Expected Behaviour

User should be provided useful debugging info when the lambda function that sets up the custom domain doesn't have the IAM permissions to do whats needed.

## Current Behavior

Right now the rescue is too general and it's a `rescue Exception`, is silent, and there's no debugging info provided.

## Step-by-step reproduction instructions

1. Deploy with a custom domain
2. Remove IAM permission to describe the stack for that custom lambda function
3. Redeploy with a custom domain

## Code Sample

* Related ticket https://github.com/boltops-tools/jets/issues/551
* Really useful comment in that ticket:  https://github.com/boltops-tools/jets/issues/551#issuecomment-849410682 Thanks @JackKelly-Bellroy 

## Solution Suggestion

When there's not enough IAM permission to describe the stack, it should log an error and hard fail so users are given info on how to fix it.

Note: One caveat is that it fails and an exception is not raise properly, cloudformation can take 2-3 hours before timing out 🤦🏻‍♂️ So need to be careful about testing this logic 👍

**Comment by JackKelly-Bellroy** [comment] 2021-05-27 23:48
Thanks for filing this. I'm not intimately familiar with Jets' internal architecture, so the following may be off-base. Posting anyway in case it's useful. It seems like the deploy process happens in three broad steps:

1. Collect facts about the environment (Is there a Route53 `RecordSet`? Are there domain-related resources deployed in the stack?)
2. Generate CloudFormation template
3. Deploy CloudFormation template

ISTM that only steps (1) and (3) need to talk to AWS: step (1) needs AWS interaction to understand what's already deployed (and should fail noisily on error - this was the root cause of #551). Step 3 needs AWS interaction to perform the deploy and is more complicated from an IAM perspective - I expect the large timeouts happen when you have resources that don't deploy properly due to permission errors. (Another thing to watch for is stacks that don't roll back properly because you have a `CreateFoo` permission but no `DeleteFoo` on the role).

Splitting the code along these lines might make it easier to test each part individually, and avoid the long deploy timeouts when you're working on the "template generation" part.

(It would be cool if there was a way to push a mock AWS client object through a piece of code, record the method calls on it, and use that to determine necessary IAM policies, but that's pretty far out of scope. I wonder if such a gem exists?)

**Comment by sam0x17** [comment] 2021-06-15 17:47
Just a note, we found with custom domains if you have an existing stack deployed and make a change to what domain/subdomain is being used, the only way to get it working properly is to delete the entire stack and re-deploy. The same goes for if you make any manual changes to the dns records

**Closed** 2023-05-25 18:42 UTC
Labels: bug, help wanted

**Comment by tongueroo** [comment] 2023-05-25 18:45
@JackKelly-Bellroy Thanks for the detailed report. Details of fix in https://github.com/boltops-tools/jets/pull/649

@sam0x17 Thanks for the note also. Will update docs with those cavaets.
