### ISSUE TITLE
Support `Time.zone`

### ISSUE THREAD

**Issue by KevinColemanInc** [boltops-tools/jets#427] opened 2020-01-07 16:56 UTC
## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |   MacOS 10.14.6      |
| Jets             |    2.3.11     |
| Ruby             |     2.5.7    |

---

## Expected Behaviour

I would expect `Time.zone` to return the system's timezone.
```
> Time.zone
 => #<ActiveSupport::TimeZone:0x00007fb0da39f200 @name="Eastern Time (US & Canada)", @utc_offset=nil, @tzinfo=#<TZInfo::DataTimezone: America/New_York>>
```

## Current Behavior

```
> Time.zone
# => nil
```

## Solution Suggestion

My guess is its not being initialized properly?

**Comment by choilive** [comment] 2020-02-24 16:35
this looks like a good first issue for me. ill give it a shot.

**Comment by einzige** [comment] 2020-03-16 14:38
Also, if you set the timezone in the initializer:

```ruby
Time.zone = 'UTC'
```

It returns nil in the app.

**Comment by jtoy** [comment] 2020-12-16 03:17
This looks fixed now, can we close?

**Comment by tongueroo** [comment] 2020-12-16 03:26
Confirmed:

```
$ jets c
Jets booting up in development mode!
=> #<ActiveSupport::TimeZone:0x0000000004096a38 @name="UTC", @utc_offset=nil, @tzinfo=#<TZInfo::DataTimezone: Etc/UTC>>
>> 
```

**Closed by tongueroo** 2020-12-16 03:26 UTC
Labels: bug, help wanted
